### ISSUE TITLE
Relax deployer dependency

### ISSUE THREAD

**Issue by bummzack** [FlorianMoser/plesk-deployer#1]
First of all, let me say thanks for this recipe. It just helped me successfully deploy to Metanet.

Your deployer dependency is hardcoded to `5.1.1` though, which isn't really helpful. I've used deployer `4.3` and it worked fine with your recipe.

I suggest you relax the version requirement to something like: `>=4.0 <6.0` 
I could imagine that it'll work with deployer v6 as well, so maybe the constraint could even be changed to `>=4.0 <7.0`

**Comment by FlorianMoser** [comment]
I'm glad if the script is useful to you.

I completely agree with you that the script is currently very tightly coupled to Deployer versions. The problem is that some task directly overwrite certain base tasks of Deployer. As soon as these tasks change in Deployer, I'll have to update them in the plesk-deployer.

I planned to update the plesk-deployer more often, but I'm currently unable to follow the fast pace of Deployer releases.

If I remember correctly, some task changed below 5.x, but I will have a look at it tomorrow and see if I can relax the dependency.

**Comment by bummzack** [comment]
Ok great. I can confirm that it works with `4.3` without modification, so this version could be added at least.

I think deployer also adhere to semantic versioning, so the API should not change with minor releases.

**Comment by FlorianMoser** [comment]
I created a branch for `4.x` and `5.x` (`4.x-dev` and `5.x-dev` on Packagist) with relaxed dependencies.

There seems to be a change or two with Deployer `6.x`. I'll first look into this in detail before I update and tag the master.
